export interface ScenarioNode {
  id: string;
  event: string;
  detail: string;
  sector: string;
  region: string;
  magnitude: number;
  unit: string;
  direction: string;
  delay_days: number;
  duration_days: number;
  confidence: number;
  source: string;
  children: string[];
}

export interface ScenarioEdge {
  source: string;
  target: string;
}

export interface ScenarioData {
  scenario: { name: string; description: string; date?: string; tags?: string[] };
  chain: { nodes: ScenarioNode[]; edges: ScenarioEdge[] };
}

function buildEdges(nodes: ScenarioNode[]): ScenarioEdge[] {
  const edges: ScenarioEdge[] = [];
  for (const node of nodes) {
    for (const childId of node.children) {
      edges.push({ source: node.id, target: childId });
    }
  }
  return edges;
}

const hormuzNodes: ScenarioNode[] = [
  { id: "hormuz_blocked", event: "Strait of Hormuz Blocked", detail: "Tanker traffic collapsed by over 90%. 20% of global oil supply and 30% of global fertilizer trade disrupted.", sector: "security", region: "middle-east", magnitude: 90, unit: "% traffic drop", direction: "blocked", delay_days: 0, duration_days: 180, confidence: 0.95, source: "Reuters, IEA March 2026", children: ["oil_supply_drop", "lng_price_surge", "fertilizer_shortage"] },
  { id: "oil_supply_drop", event: "Global Oil Supply -8M barrels/day", detail: "8% of world demand removed. Gulf countries cut production 10M+ bpd.", sector: "energy", region: "global", magnitude: 8, unit: "% supply cut", direction: "down", delay_days: 1, duration_days: 180, confidence: 0.95, source: "IEA March 2026", children: ["oil_price_surge", "fuel_price_spike"] },
  { id: "oil_price_surge", event: "Brent Crude Surges to $119/barrel", detail: "Oil prices jumped nearly 40% from pre-conflict levels.", sector: "energy", region: "global", magnitude: 40, unit: "%", direction: "up", delay_days: 3, duration_days: 180, confidence: 0.95, source: "Reuters, World Bank", children: ["transport_cost_rise", "manufacturing_cost"] },
  { id: "fuel_price_spike", event: "Retail Fuel Prices Spike +35%", detail: "Gasoline prices surge globally. Turkey: benzin 48 to 67 TRY/L.", sector: "transport", region: "global", magnitude: 35, unit: "%", direction: "up", delay_days: 7, duration_days: 180, confidence: 0.9, source: "Reuters March 2026", children: ["personal_fuel_cost"] },
  { id: "personal_fuel_cost", event: "Your Monthly Fuel Cost Increases", detail: "Direct impact on personal transportation budget.", sector: "transport", region: "personal", magnitude: 35, unit: "%", direction: "up", delay_days: 7, duration_days: 180, confidence: 0.9, source: "Calculated", children: [] },
  { id: "lng_price_surge", event: "LNG Prices Surge +66%", detail: "Liquefied natural gas prices nearly doubled.", sector: "energy", region: "global", magnitude: 66, unit: "%", direction: "up", delay_days: 7, duration_days: 180, confidence: 0.9, source: "World Bank", children: ["electricity_bill_rise"] },
  { id: "electricity_bill_rise", event: "Electricity & Heating Bills +30%", detail: "Natural gas powers ~40% of electricity. Bills rise with 1-3 month lag.", sector: "energy", region: "global", magnitude: 30, unit: "%", direction: "up", delay_days: 45, duration_days: 180, confidence: 0.8, source: "OECD estimates", children: [] },
  { id: "fertilizer_shortage", event: "Global Fertilizer Supply -30%", detail: "30% of fertilizer trade transits Hormuz. Prices surged 50%.", sector: "food", region: "global", magnitude: 50, unit: "% price rise", direction: "up", delay_days: 14, duration_days: 365, confidence: 0.9, source: "FAO, Bloomberg", children: ["wheat_price_rise", "crop_yield_drop"] },
  { id: "wheat_price_rise", event: "Wheat & Grain Prices +22%", detail: "Fertilizer costs pass through to grain prices.", sector: "food", region: "global", magnitude: 22, unit: "%", direction: "up", delay_days: 60, duration_days: 365, confidence: 0.85, source: "FAO, Helios AI", children: ["bread_price", "food_general"] },
  { id: "crop_yield_drop", event: "Crop Yields Decline -15%", detail: "Nitrogen-intensive crops exposed during planting season.", sector: "food", region: "global", magnitude: 15, unit: "% yield drop", direction: "down", delay_days: 120, duration_days: 365, confidence: 0.75, source: "AgFunder News", children: ["food_general"] },
  { id: "bread_price", event: "Bread, Pasta, Flour Prices +18%", detail: "Wheat-based staples directly affected.", sector: "food", region: "global", magnitude: 18, unit: "%", direction: "up", delay_days: 90, duration_days: 365, confidence: 0.85, source: "Helios AI", children: ["grocery_bill_impact"] },
  { id: "food_general", event: "Overall Food Prices +15%", detail: "Combined fertilizer + transport + yield impact.", sector: "food", region: "global", magnitude: 15, unit: "%", direction: "up", delay_days: 120, duration_days: 365, confidence: 0.8, source: "Helios AI", children: ["grocery_bill_impact"] },
  { id: "grocery_bill_impact", event: "Your Grocery Bill Increases", detail: "Direct impact on food budget.", sector: "food", region: "personal", magnitude: 18, unit: "%", direction: "up", delay_days: 90, duration_days: 365, confidence: 0.8, source: "Calculated", children: [] },
  { id: "transport_cost_rise", event: "Commercial Transport +25%", detail: "Trucking, shipping, freight costs surge.", sector: "transport", region: "global", magnitude: 25, unit: "%", direction: "up", delay_days: 14, duration_days: 180, confidence: 0.85, source: "OECD, PMI data", children: ["food_general"] },
  { id: "manufacturing_cost", event: "Manufacturing Costs Rise, PMIs Fall", detail: "Eurozone PMI fell to 10-month low. Stagflation risk.", sector: "employment", region: "global", magnitude: 5, unit: "% cost rise", direction: "up", delay_days: 30, duration_days: 365, confidence: 0.8, source: "Reuters", children: [] },
];

const dollarNodes: ScenarioNode[] = [
  { id: "dollar_drop", event: "Dollar Reserve Share Falls Below 50%", detail: "First time since WWII. BRICS mBridge bypasses SWIFT.", sector: "currency", region: "global", magnitude: 30, unit: "% decline", direction: "down", delay_days: 0, duration_days: 730, confidence: 0.7, source: "CFO Times 2026", children: ["gold_surge", "dollar_index_fall", "us_debt_spiral"] },
  { id: "gold_surge", event: "Gold Surges Past $6,000/oz", detail: "Central banks accelerate purchases. 77% plan to increase reserves.", sector: "finance", region: "global", magnitude: 50, unit: "%", direction: "up", delay_days: 30, duration_days: 365, confidence: 0.65, source: "BIS data", children: ["crypto_surge"] },
  { id: "crypto_surge", event: "Crypto Markets Rally as Dollar Alternative", detail: "Bitcoin and tokenized gold see massive inflows.", sector: "finance", region: "global", magnitude: 80, unit: "%", direction: "up", delay_days: 14, duration_days: 365, confidence: 0.5, source: "On-chain data", children: [] },
  { id: "dollar_index_fall", event: "Dollar Index (DXY) Drops 15%", detail: "Major currencies strengthen. Yuan rises to 5%+ reserve share.", sector: "currency", region: "global", magnitude: 15, unit: "%", direction: "down", delay_days: 7, duration_days: 365, confidence: 0.6, source: "Forex markets", children: ["emerging_pressure", "import_cost"] },
  { id: "emerging_pressure", event: "Emerging Market Currency Volatility", detail: "Turkish lira, peso, pound face pressure despite dollar weakness.", sector: "currency", region: "emerging", magnitude: 20, unit: "% volatility", direction: "up", delay_days: 14, duration_days: 365, confidence: 0.7, source: "Historical patterns", children: ["local_inflation"] },
  { id: "local_inflation", event: "EM Inflation Accelerates to 35%+", detail: "Currency volatility feeds into consumer prices.", sector: "currency", region: "emerging", magnitude: 35, unit: "% CPI", direction: "up", delay_days: 60, duration_days: 365, confidence: 0.7, source: "TCMB, IMF", children: ["purchasing_power"] },
  { id: "purchasing_power", event: "Your Purchasing Power Erodes", detail: "Salary flat while prices rise. Real income drops 25%.", sector: "currency", region: "personal", magnitude: 25, unit: "% real loss", direction: "down", delay_days: 90, duration_days: 365, confidence: 0.7, source: "Calculated", children: [] },
  { id: "import_cost", event: "Import Costs Rise +12%", detail: "Trade disruption raises costs for importing nations.", sector: "food", region: "global", magnitude: 12, unit: "%", direction: "up", delay_days: 30, duration_days: 365, confidence: 0.65, source: "WTO data", children: ["food_import"] },
  { id: "food_import", event: "Food Import Bills Rise +15%", detail: "Net food importers face higher bills.", sector: "food", region: "emerging", magnitude: 15, unit: "%", direction: "up", delay_days: 60, duration_days: 365, confidence: 0.7, source: "FAO", children: ["grocery"] },
  { id: "grocery", event: "Your Grocery Spending Increases", detail: "Import-dependent food items more expensive.", sector: "food", region: "personal", magnitude: 15, unit: "%", direction: "up", delay_days: 90, duration_days: 365, confidence: 0.7, source: "Calculated", children: [] },
  { id: "us_debt_spiral", event: "US Debt Servicing Costs Explode", detail: "Interest exceeds $1.2T/year. Budget squeeze.", sector: "finance", region: "us", magnitude: 20, unit: "% of budget", direction: "up", delay_days: 0, duration_days: 730, confidence: 0.8, source: "US Treasury, CBO", children: ["risk_repricing"] },
  { id: "risk_repricing", event: "Global Markets Correct 20%+", detail: "Safe-haven flight. EM bonds sell off.", sector: "finance", region: "global", magnitude: 20, unit: "% decline", direction: "down", delay_days: 30, duration_days: 180, confidence: 0.55, source: "Historical analysis", children: [] },
];

const aiNodes: ScenarioNode[] = [
  { id: "ai_threshold", event: "Agentic AI Automates 40% of Knowledge Tasks", detail: "AI agents plan, execute autonomously. 62% of enterprises scaling.", sector: "technology", region: "global", magnitude: 40, unit: "% tasks", direction: "up", delay_days: 0, duration_days: 730, confidence: 0.8, source: "WEF 2025, Forrester", children: ["entry_collapse", "mid_pressure", "degree_devalue"] },
  { id: "entry_collapse", event: "Entry-Level Tech Hiring -50%", detail: "Junior dev, data entry, support, content roles automated first.", sector: "employment", region: "global", magnitude: 50, unit: "% cut", direction: "down", delay_days: 0, duration_days: 730, confidence: 0.85, source: "LinkedIn, AI Displacement Index", children: ["youth_unemp", "wage_stagnate"] },
  { id: "mid_pressure", event: "Mid-Level Roles Under Pressure", detail: "Accountants, analysts, PMs face augmentation. 41% leaders cut headcount.", sector: "employment", region: "global", magnitude: 25, unit: "% at risk", direction: "down", delay_days: 90, duration_days: 730, confidence: 0.7, source: "McKinsey", children: ["wage_stagnate", "spending_drop"] },
  { id: "degree_devalue", event: "University Degrees Lose Value", detail: "Employment rate 78% to 54%. Knowledge half-life: 18-24 months.", sector: "technology", region: "global", magnitude: 30, unit: "% value loss", direction: "down", delay_days: 30, duration_days: 730, confidence: 0.8, source: "Bipartisan Policy Center", children: ["skills_pivot"] },
  { id: "youth_unemp", event: "Youth Unemployment Surges 20%+", detail: "22 applicants per job. Turkey youth at 14.9%.", sector: "employment", region: "global", magnitude: 20, unit: "%", direction: "up", delay_days: 60, duration_days: 730, confidence: 0.75, source: "ILO", children: ["mental_health", "your_risk"] },
  { id: "wage_stagnate", event: "Wages Stagnate Despite Productivity", detail: "Headcount -12%, revenue +8.3%. Gains don't reach workers.", sector: "employment", region: "global", magnitude: 8, unit: "% real decline", direction: "down", delay_days: 120, duration_days: 730, confidence: 0.75, source: "Enterprise data", children: ["spending_drop"] },
  { id: "spending_drop", event: "Consumer Spending Contracts", detail: "52% can't pay bills. Credit card debt rising.", sector: "finance", region: "global", magnitude: 8, unit: "%", direction: "down", delay_days: 180, duration_days: 365, confidence: 0.7, source: "Gallup 2026", children: ["biz_close"] },
  { id: "biz_close", event: "Small Business Closures Accelerate", detail: "82% cite cash flow. Main streets hollow out.", sector: "employment", region: "global", magnitude: 15, unit: "% increase", direction: "up", delay_days: 240, duration_days: 365, confidence: 0.65, source: "Fed Survey 2026", children: [] },
  { id: "skills_pivot", event: "Mass Reskilling Demand Emerges", detail: "44% of skills need updating. New roles forming.", sector: "technology", region: "global", magnitude: 44, unit: "% gap", direction: "up", delay_days: 30, duration_days: 730, confidence: 0.85, source: "WEF", children: ["new_roles"] },
  { id: "new_roles", event: "170M New Jobs Form by 2030", detail: "Agent Orchestrators, AI Calibrators, Autonomy Designers.", sector: "employment", region: "global", magnitude: 170, unit: "M roles", direction: "up", delay_days: 180, duration_days: 1460, confidence: 0.7, source: "WEF", children: [] },
  { id: "mental_health", event: "Loneliness & Anxiety Epidemic", detail: "1 in 6 lonely. 3x depression in young adults. $406B toll.", sector: "health", region: "global", magnitude: 33, unit: "% adults", direction: "up", delay_days: 90, duration_days: 730, confidence: 0.8, source: "WHO, Edelman 2026", children: [] },
  { id: "your_risk", event: "Your Job Automation Risk", detail: "Individual risk based on task composition and industry.", sector: "employment", region: "personal", magnitude: 45, unit: "% avg risk", direction: "up", delay_days: 0, duration_days: 730, confidence: 0.6, source: "AI Exposure (45.8M at high risk)", children: [] },
];

const pandemicNodes: ScenarioNode[] = [
  { id: "pandemic_declared", event: "WHO Declares H5N1 Pandemic", detail: "Novel avian flu variant achieves R0 of 2.5+. Sustained clusters spread to 30+ countries.", sector: "health", region: "global", magnitude: 100, unit: "% alert", direction: "disrupted", delay_days: 0, duration_days: 365, confidence: 0.35, source: "Hypothetical (WHO risk)", children: ["travel_restrict", "supply_shock", "market_panic"] },
  { id: "travel_restrict", event: "Global Travel Restrictions", detail: "International air travel drops 60-80%. Border closures across Asia and Europe.", sector: "transport", region: "global", magnitude: 70, unit: "% reduction", direction: "down", delay_days: 7, duration_days: 180, confidence: 0.6, source: "COVID precedent", children: ["tourism_hit", "service_hit"] },
  { id: "tourism_hit", event: "Tourism & Hospitality Collapse", detail: "Hotels, restaurants, airlines face 50% revenue loss. Turkey tourism at risk.", sector: "employment", region: "global", magnitude: 50, unit: "% revenue loss", direction: "down", delay_days: 14, duration_days: 270, confidence: 0.65, source: "UNWTO, COVID precedent", children: ["unemployment"] },
  { id: "supply_shock", event: "Global Supply Chains Disrupted", detail: "Factory closures in Asia. Already fragile from Hormuz crisis.", sector: "transport", region: "global", magnitude: 30, unit: "% disruption", direction: "disrupted", delay_days: 14, duration_days: 270, confidence: 0.6, source: "Supply chain analysis", children: ["medicine", "food_disruption"] },
  { id: "medicine", event: "Medicine & Medical Supply Shortage", detail: "80% of antibiotic ingredients from Asia. Vaccine ramp is slow.", sector: "health", region: "global", magnitude: 40, unit: "% supply drop", direction: "down", delay_days: 30, duration_days: 180, confidence: 0.55, source: "WHO supply reports", children: [] },
  { id: "food_disruption", event: "Compound Food Crisis (War + Pandemic)", detail: "Pandemic + Hormuz + fertilizer = triple threat to food security.", sector: "food", region: "global", magnitude: 25, unit: "% price rise", direction: "up", delay_days: 30, duration_days: 365, confidence: 0.55, source: "FAO compound modeling", children: ["your_food"] },
  { id: "your_food", event: "Your Food Costs Surge", detail: "Compound crisis creates severe household budget pressure.", sector: "food", region: "personal", magnitude: 25, unit: "%", direction: "up", delay_days: 45, duration_days: 365, confidence: 0.55, source: "Calculated", children: [] },
  { id: "market_panic", event: "Financial Markets Crash 25%", detail: "VIX spikes above 50. Already fragile markets face pandemic shock.", sector: "finance", region: "global", magnitude: 25, unit: "% decline", direction: "down", delay_days: 3, duration_days: 180, confidence: 0.6, source: "COVID crash precedent", children: ["credit_freeze"] },
  { id: "credit_freeze", event: "Credit Markets Tighten Sharply", detail: "Banks restrict lending. Mortgage rates spike.", sector: "finance", region: "global", magnitude: 30, unit: "% tightening", direction: "up", delay_days: 14, duration_days: 270, confidence: 0.55, source: "2020 credit analysis", children: [] },
  { id: "service_hit", event: "Service Sector Employment Drops", detail: "59.3% of Turkish employment in services. Lockdowns hit hardest.", sector: "employment", region: "emerging", magnitude: 20, unit: "% at risk", direction: "down", delay_days: 14, duration_days: 270, confidence: 0.6, source: "TurkStat", children: ["unemployment"] },
  { id: "unemployment", event: "Compound Unemployment Surge to 35%+", detail: "War + AI + pandemic = perfect storm. Turkey real unemployment could exceed 35%.", sector: "employment", region: "global", magnitude: 35, unit: "% real", direction: "up", delay_days: 60, duration_days: 365, confidence: 0.5, source: "Compound crisis projection", children: [] },
];

const taiwanNodes: ScenarioNode[] = [
  { id: "strait_blockade_chips", event: "Taiwan Strait closed to commercial chip and fab inbound traffic", detail: "Industry analysts attribute roughly 60% of global foundry revenue and over 90% of leading-edge (<7 nm) logic to Taiwan (TSMC, UMC). A blockade idles fabs and stops lithography chemistry and wafer deliveries within days.", sector: "security", region: "emerging", magnitude: 60, unit: "% of global foundry capacity at risk", direction: "blocked", delay_days: 0, duration_days: 270, confidence: 0.72, source: "SIA Factbook 2024; TrendForce foundry share data", children: ["wafer_inbound_stop", "war_risk_shipping"] },
  { id: "war_risk_shipping", event: "Maritime war-risk premiums and rerouting add weeks of lead time", detail: "Baltic Exchange war-risk pricing for the Strait spiked in prior Red Sea–style shocks by triple-digit percent; carriers divert via longer routes or idle.", sector: "transport", region: "global", magnitude: 120, unit: "% insurance premium increase (route analog)", direction: "up", delay_days: 3, duration_days: 180, confidence: 0.68, source: "Reuters shipping insurance reporting; IMF trade disruption notes", children: ["logic_wafer_shortage"] },
  { id: "wafer_inbound_stop", event: "Photoresist, specialty gases, and wafer stockpiles deplete at fabs", detail: "Leading-edge fabs typically hold limited buffer; TSMC has noted supply-chain concentration in materials. Disruption beyond 2–4 weeks forces utilization cuts industry-wide.", sector: "technology", region: "global", magnitude: 35, unit: "% utilization reduction (scenario band)", direction: "down", delay_days: 14, duration_days: 240, confidence: 0.7, source: "Company 10-K supply disclosures; SEMI materials reports", children: ["logic_wafer_shortage"] },
  { id: "logic_wafer_shortage", event: "Advanced-node logic and memory allocation rationed to OEMs", detail: "Smartphones, PCs, and servers compete for the same leading-edge wafers; historical 2020–2022 chip shortage added ~$210B in lost auto revenue per AlixPartners estimates.", sector: "technology", region: "global", magnitude: 45, unit: "% backlog extension vs baseline", direction: "disrupted", delay_days: 30, duration_days: 365, confidence: 0.75, source: "AlixPartners May 2022 semiconductor shortage analysis", children: ["oem_bom_inflation", "automotive_mcu_crisis"] },
  { id: "oem_bom_inflation", event: "Electronics bill-of-materials costs jump for phones, PCs, servers", detail: "During 2021–2022, discrete component price spikes passed through; server and GPU pricing rose sharply amid allocation.", sector: "technology", region: "global", magnitude: 28, unit: "% BOM cost increase (analog period)", direction: "up", delay_days: 45, duration_days: 365, confidence: 0.73, source: "IDC hardware pricing commentary; Gartner IT spending data", children: ["retail_device_price_spike"] },
  { id: "retail_device_price_spike", event: "Consumer electronics shelf prices rise", detail: "Historical correlation: when memory and logic tighten, PC and handset ASPs increase; OEMs cite component costs in earnings.", sector: "technology", region: "us", magnitude: 18, unit: "% ASP increase", direction: "up", delay_days: 60, duration_days: 365, confidence: 0.7, source: "Consumer Technology Association trend data; OEM earnings calls", children: ["personal_device_budget"] },
  { id: "automotive_mcu_crisis", event: "Vehicle assembly lines slow for lack of MCUs and power semis", detail: "2021 chip shortage cut global light-vehicle output by ~11 million units (IHS/S&P estimates). Taiwan-heavy supply magnifies a repeat.", sector: "transport", region: "global", magnitude: 11, unit: "million vehicles output at risk (analog magnitude)", direction: "down", delay_days: 21, duration_days: 365, confidence: 0.74, source: "S&P Global Mobility; McKinsey automotive semiconductor analysis", children: ["auto_tier_layoffs"] },
  { id: "auto_tier_layoffs", event: "Automotive and electronics suppliers announce workforce reductions", detail: "During 2022–2023 tech retrenchment, US tech layoffs exceeded 150k in peak-year trackers; auto supplier cuts tracked production schedules.", sector: "employment", region: "global", magnitude: 12, unit: "% headcount reduction (sector stress scenario)", direction: "down", delay_days: 90, duration_days: 540, confidence: 0.65, source: "Layoffs.fyi; BLS manufacturing employment series", children: ["services_inflation_feedthrough"] },
  { id: "services_inflation_feedthrough", event: "Sticky services and repair inflation as durable goods stay expensive", detail: "Core CPI persistence in 2022–2024 showed services lagging goods; high device and vehicle costs extend replacement cycles and repair demand.", sector: "finance", region: "us", magnitude: 3.5, unit: "percentage points core CPI contribution (illustrative)", direction: "up", delay_days: 120, duration_days: 730, confidence: 0.62, source: "Bureau of Labor Statistics CPI; Fed staff research on persistence", children: ["personal_real_income_squeeze"] },
  { id: "personal_device_budget", event: "Your spending on phones, laptops, and upgrades rises", detail: "Direct pass-through from higher ASPs and fewer promotions; households delay refresh cycles or pay more at purchase.", sector: "technology", region: "personal", magnitude: 18, unit: "%", direction: "up", delay_days: 60, duration_days: 365, confidence: 0.68, source: "calculated from retail_device_price_spike node", children: [] },
  { id: "personal_real_income_squeeze", event: "Your real wages buy less as layoff risk and inflation combine", detail: "Joint effect of higher goods prices and labor-market slack in exposed sectors on household budgets.", sector: "employment", region: "personal", magnitude: 4, unit: "% real income drag", direction: "down", delay_days: 150, duration_days: 730, confidence: 0.6, source: "calculated composite", children: [] },
];

const climateNodes: ScenarioNode[] = [
  { id: "sync_extreme_weather", event: "Droughts and floods hit Argentina, EU, and South Asia in one season", detail: "FAO food price index rose sharply in 2022 after Ukraine war and weather shocks; multi-breadbasket failure is a documented tail risk in IPCC and agricultural economics literature.", sector: "food", region: "global", magnitude: 18, unit: "% global wheat output at risk (scenario)", direction: "down", delay_days: 0, duration_days: 365, confidence: 0.66, source: "FAO Food Price Index history; IPCC WGII food security chapter", children: ["grain_yield_shock", "rice_disruption"] },
  { id: "rice_disruption", event: "Asian rice belts see uneven monsoon and heat stress", detail: "India banned non-basmati white rice exports in 2023 (~10M tonnes); price-sensitive consumers face abrupt rationing when exporters tighten.", sector: "food", region: "emerging", magnitude: 22, unit: "% exportable surplus reduction", direction: "down", delay_days: 30, duration_days: 365, confidence: 0.71, source: "Reuters India export ban 2023; USDA PSD rice data", children: ["grain_trade_fragmentation"] },
  { id: "grain_yield_shock", event: "Corn and soybean yields fall in Argentina and southern Brazil", detail: "2022–2023 La Niña already cut Argentine soy; combined corn/soy shortfalls move Chicago futures sharply.", sector: "food", region: "emerging", magnitude: 25, unit: "% yield deviation from trend", direction: "down", delay_days: 45, duration_days: 365, confidence: 0.69, source: "USDA WASDE; CONAB Brazil crop reports", children: ["grain_trade_fragmentation"] },
  { id: "grain_trade_fragmentation", event: "Export bans and licensing slow global grain flow", detail: "After 2022, 20+ countries imposed food export restrictions per IFPRI tracker; fragmentation adds 15–30 day delivery uncertainty.", sector: "food", region: "global", magnitude: 30, unit: "% increase in delivery lead time", direction: "disrupted", delay_days: 14, duration_days: 540, confidence: 0.74, source: "IFPRI export restriction tracker; World Bank trade briefs", children: ["wheat_corn_price_spike"] },
  { id: "wheat_corn_price_spike", event: "Wheat and corn futures jump to multi-year highs", detail: "CBOT wheat exceeded $12/bushel in 2022; corn peaked near $8. A synchronized shortfall could approach those bands adjusted for 2026 baseline.", sector: "food", region: "global", magnitude: 45, unit: "% price increase vs 5-year avg", direction: "up", delay_days: 30, duration_days: 365, confidence: 0.72, source: "CME Group settlement data; FAO cereal price sub-index", children: ["feed_cost_explosion"] },
  { id: "feed_cost_explosion", event: "Livestock feed costs surge, squeezing producer margins", detail: "Feed is ~50–70% of variable costs for intensive livestock; 2022 U.S. farm sector saw record cost inflation per USDA ERS.", sector: "food", region: "global", magnitude: 35, unit: "% feed cost increase", direction: "up", delay_days: 60, duration_days: 730, confidence: 0.7, source: "USDA ERS livestock sector briefs", children: ["meat_dairy_price_rise"] },
  { id: "meat_dairy_price_rise", event: "Retail meat and dairy inflation accelerates", detail: "OECD–FAO outlook links feed costs to animal product prices with 3–9 month lag; 2022 EU retail meat rose high single digits YoY.", sector: "food", region: "global", magnitude: 15, unit: "% YoY retail increase", direction: "up", delay_days: 120, duration_days: 730, confidence: 0.68, source: "OECD-FAO Agricultural Outlook; Eurostat HICP food", children: ["headline_food_cpi"] },
  { id: "headline_food_cpi", event: "National food CPI prints double-digit in import-dependent states", detail: "2022 saw Turkey food inflation >90% YoY; Egypt bread subsidy strain; many EM food weights in CPI exceed 30%.", sector: "food", region: "emerging", magnitude: 40, unit: "% YoY food CPI (stress case)", direction: "up", delay_days: 90, duration_days: 730, confidence: 0.64, source: "IMF World Economic Outlook food inflation tables; national statistical offices", children: ["street_protests_em"] },
  { id: "street_protests_em", event: "Food-price protests and political instability rise", detail: "ACLED and World Bank link food spikes to unrest; 2007–2008 and 2010–2011 episodes show rapid cascade from prices to politics.", sector: "security", region: "emerging", magnitude: 200, unit: "% increase in protest events (illustrative index)", direction: "up", delay_days: 120, duration_days: 365, confidence: 0.58, source: "ACLED conflict data; World Bank food riot literature", children: ["personal_grocery_stress"] },
  { id: "personal_grocery_stress", event: "Your weekly grocery spend rises and staple choices narrow", detail: "Household food budget share increases fastest for lowest income quintiles; substitution toward calories over diversity.", sector: "food", region: "personal", magnitude: 22, unit: "% budget increase", direction: "up", delay_days: 60, duration_days: 730, confidence: 0.65, source: "calculated from headline_food_cpi pass-through", children: [] },
];

const earthquakeNodes: ScenarioNode[] = [
  { id: "istanbul_m75_rupture", event: "M7.5+ earthquake strikes Istanbul urban corridor", detail: "USGS and Turkish disaster agencies cite high probability of M7+ Marmara event; 1999 İzmit earthquake M7.6 killed >17,000. Istanbul hosts ~16M+ people in dense unreinforced stock.", sector: "security", region: "emerging", magnitude: 7.6, unit: "Mw", direction: "disrupted", delay_days: 0, duration_days: 30, confidence: 0.55, source: "USGS seismic hazard; AFAD Turkey historical catalogs", children: ["infrastructure_collapse", "port_logistics_halt"] },
  { id: "port_logistics_halt", event: "Marmara ports and bridges impair national goods flow", detail: "Istanbul handles large share of Turkey’s trade; bridge and tunnel damage in scenarios reroutes freight, adding 20–40% inland transport time.", sector: "transport", region: "emerging", magnitude: 35, unit: "% freight delay", direction: "disrupted", delay_days: 1, duration_days: 180, confidence: 0.62, source: "World Bank disaster logistics studies; Turkish Ministry of Transport briefs", children: ["construction_material_shortage"] },
  { id: "infrastructure_collapse", event: "Water, power, and hospital capacity collapse in worst-hit districts", detail: "WHO post-earthquake reports show mortality tied to medical surge; 2023 Kahramanmaraş sequence displaced >3M with widespread utility outages.", sector: "health", region: "emerging", magnitude: 40, unit: "% service disruption in metro area", direction: "down", delay_days: 0, duration_days: 120, confidence: 0.65, source: "WHO Türkiye earthquake reports; UNDRR damage assessments", children: ["mass_displacement"] },
  { id: "mass_displacement", event: "2–5 million residents seek temporary shelter outside hazard zone", detail: "AFAD camp counts after 2023 exceeded 300k sites; a Marmara event implies multi-million displacement per modeled scenarios.", sector: "housing", region: "emerging", magnitude: 3000000, unit: "people displaced (range)", direction: "up", delay_days: 1, duration_days: 1095, confidence: 0.58, source: "UN OCHA displacement estimates; Turkish Red Crescent planning figures", children: ["housing_stock_loss"] },
  { id: "housing_stock_loss", event: "Hundreds of thousands of housing units uninhabitable", detail: "2023 earthquakes damaged >230k buildings in Turkey per government damage surveys; Istanbul’s building stock mix implies comparable or larger uninhabitable counts in M7.5+ scenario.", sector: "housing", region: "emerging", magnitude: 300000, unit: "units heavy damage or collapse (scenario)", direction: "collapsed", delay_days: 0, duration_days: 3650, confidence: 0.57, source: "Turkish Ministry reports post-2023; World Bank Türkiye rapid damage assessment", children: ["insurance_solvency_stress"] },
  { id: "construction_material_shortage", event: "Cement and steel prices spike as rebuild competes with regional demand", detail: "Post-2023 Türkiye saw cement price volatility; import bills for steel rose with reconstruction demand.", sector: "housing", region: "emerging", magnitude: 40, unit: "% wholesale price increase", direction: "up", delay_days: 30, duration_days: 730, confidence: 0.63, source: "TurkStat producer prices; TCMB sector reports", children: ["gdp_contraction_risk"] },
  { id: "insurance_solvency_stress", event: "Domestic insurers face claims exceeding reinsurance towers", detail: "Turkish Catastrophe Insurance Pool (TCIP) covers residential; large industrial and commercial lines hit global reinsurers. 2023 event produced tens of billions USD in economic losses.", sector: "finance", region: "emerging", magnitude: 50, unit: "billion USD economic loss (order-of-magnitude band)", direction: "down", delay_days: 14, duration_days: 365, confidence: 0.52, source: "World Bank disaster loss estimates; Swiss Re sigma natural catastrophe reports", children: ["gdp_contraction_risk"] },
  { id: "gdp_contraction_risk", event: "National GDP dips and lira volatility spikes on reconstruction financing", detail: "TCMB and IMF work shows large shocks raise financing needs; 2023 earthquake contributed to growth revision and wider external deficit.", sector: "currency", region: "emerging", magnitude: 3, unit: "% GDP contraction year-one (scenario)", direction: "down", delay_days: 90, duration_days: 730, confidence: 0.54, source: "IMF Türkiye Article IV; TCMB inflation reports", children: ["internal_migration_rent"] },
  { id: "internal_migration_rent", event: "Rent inflation surges in Ankara, Izmir, Antalya as evacuees arrive", detail: "Internal migration after 2023 tightened rental markets in receiving cities; Turkish CPI rent component remained elevated.", sector: "housing", region: "emerging", magnitude: 85, unit: "% YoY rent increase in hot markets (stress)", direction: "up", delay_days: 60, duration_days: 1095, confidence: 0.6, source: "TurkStat CPI rent; academic migration studies post-2023", children: ["personal_rent_burden"] },
  { id: "personal_rent_burden", event: "Your rent or mortgage + repair costs dominate monthly cash flow", detail: "Tenants in receiver cities face bidding wars; owners in damaged stock face demolition/rebuild uncertainty.", sector: "housing", region: "personal", magnitude: 50, unit: "% housing cost share of income", direction: "up", delay_days: 45, duration_days: 1095, confidence: 0.58, source: "calculated household stress index", children: [] },
];

const cryptoNodes: ScenarioNode[] = [
  { id: "market_wide_liquidation", event: "Crypto total market cap falls over 80% from cycle peak", detail: "Bitcoin fell roughly 77% peak-to-trough in 2022; broad altcoin indices fell more. An 80%+ aggregate crash implies multi-trillion notional destroyed.", sector: "finance", region: "global", magnitude: 80, unit: "% drawdown from peak", direction: "down", delay_days: 0, duration_days: 180, confidence: 0.62, source: "CoinMetrics; Bloomberg 2022 crypto market peak-to-trough data", children: ["stablecoin_depeg", "exchange_insolvency_risk", "household_crypto_losses"] },
  { id: "household_crypto_losses", event: "Retail and small-business crypto balances mark down sharply", detail: "Federal Reserve Survey of Consumer Finances and ECB household reports show non-trivial crypto participation; wealth effect hits discretionary spending.", sector: "finance", region: "us", magnitude: 500, unit: "billion USD paper wealth loss (illustrative)", direction: "down", delay_days: 0, duration_days: 90, confidence: 0.58, source: "Fed SCF 2022; Bank for International Settlements crypto exposure studies", children: ["personal_wealth_shock"] },
  { id: "exchange_insolvency_risk", event: "Major centralized exchanges halt withdrawals amid runs", detail: "FTX November 2022 showed rapid freezes; customer assets became bankruptcy claims—Chainalysis documented large on-chain outflows during stress.", sector: "finance", region: "global", magnitude: 40, unit: "% of CEX activity impaired (scenario)", direction: "disrupted", delay_days: 1, duration_days: 120, confidence: 0.58, source: "Chainalysis 2023 crypto crime report; FTX bankruptcy docket", children: ["counterparty_credit_tightening"] },
  { id: "stablecoin_depeg", event: "Large stablecoins break peg; tens of billions of dollars flee", detail: "Terra/UST lost peg May 2022 erasing on the order of $40B; USDC traded near $0.87 intraday March 2023 during SVB stress.", sector: "finance", region: "global", magnitude: 13, unit: "% max depeg from par (major stress analog)", direction: "down", delay_days: 0, duration_days: 90, confidence: 0.65, source: "Board of Governors Federal Reserve, Money and Payments discussion papers; CoinDesk Terra coverage", children: ["counterparty_credit_tightening"] },
  { id: "counterparty_credit_tightening", event: "Banks and brokers cut crypto prime brokerage and deposit relationships", detail: "Post-2022, several U.S. crypto-facing banks failed or exited; Basel finalized stricter bank capital treatment for crypto exposures.", sector: "finance", region: "us", magnitude: 50, unit: "% reduction in bank crypto on-ramp capacity (scenario)", direction: "down", delay_days: 14, duration_days: 365, confidence: 0.7, source: "FDIC Silicon Valley Bank report; Basel Committee standard on crypto exposures", children: ["hedge_fund_redemptions"] },
  { id: "hedge_fund_redemptions", event: "Crypto-native and macro funds face margin calls and investor redemptions", detail: "Three Arrows, Celsius, and lenders illustrated leverage chains; industry-wide asset management losses in 2022 were widely reported in the tens of billions.", sector: "finance", region: "global", magnitude: 100, unit: "billion USD notional stress (order of magnitude)", direction: "down", delay_days: 30, duration_days: 365, confidence: 0.55, source: "Bloomberg crypto hedge fund coverage; public bankruptcy filings", children: ["credit_spreads_widen"] },
  { id: "credit_spreads_widen", event: "High-yield and leveraged loan spreads widen in risk-off", detail: "ICE BofA US High Yield OAS exceeded 600 bps in June 2022; syndicated loan markets price higher defaults when financial conditions tighten.", sector: "finance", region: "us", magnitude: 250, unit: "basis points HY OAS widening (illustrative episode)", direction: "up", delay_days: 45, duration_days: 365, confidence: 0.63, source: "Federal Reserve Financial Stability Report; ICE BofA US High Yield index", children: ["vc_funding_freeze"] },
  { id: "vc_funding_freeze", event: "Global venture deal value for tech falls sharply", detail: "Crunchbase and PitchBook data show VC activity dropped materially in 2022–2023; crypto and growth equity were disproportionately hit.", sector: "finance", region: "us", magnitude: 45, unit: "% YoY drop in VC invested (cycle analog)", direction: "down", delay_days: 60, duration_days: 540, confidence: 0.66, source: "PitchBook NVCA Venture Monitor; Crunchbase annual reports", children: ["tech_startup_layoffs"] },
  { id: "tech_startup_layoffs", event: "Technology companies announce broad layoffs as runway shortens", detail: "Layoffs.fyi tracked more than 150,000 tech layoffs in 2022 at major employers; smaller startups cut deeper in percentage terms.", sector: "employment", region: "us", magnitude: 150000, unit: "job cuts (annual peak-year analog)", direction: "down", delay_days: 90, duration_days: 365, confidence: 0.64, source: "Layoffs.fyi; BLS CES tech-heavy industries", children: ["personal_job_insecurity"] },
  { id: "personal_wealth_shock", event: "Your crypto and risk-asset holdings lose most of their value", detail: "Direct household impact from exchange limits and token depreciation on wallets and retirement accounts with crypto ETPs.", sector: "finance", region: "personal", magnitude: 80, unit: "% portfolio loss on crypto sleeve", direction: "down", delay_days: 0, duration_days: 120, confidence: 0.6, source: "calculated", children: [] },
  { id: "personal_job_insecurity", event: "Your job search or gig income worsens in a funding winter", detail: "Hiring freezes and offer rescinds concentrated in tech and crypto-adjacent roles; duration of unemployment rises for affected cohorts.", sector: "employment", region: "personal", magnitude: 35, unit: "% longer time-to-offer vs baseline", direction: "up", delay_days: 120, duration_days: 540, confidence: 0.57, source: "calculated from vc_funding_freeze transmission", children: [] },
];

const energyNodes: ScenarioNode[] = [
  { id: "global_oil_demand_peak", event: "World oil demand stops growing and enters gentle decline", detail: "IEA Oil Market Report and World Energy Outlook scenarios show demand plateauing then falling under stated policies; peak timing debated but directionally supported by EV sales curves.", sector: "energy", region: "global", magnitude: 2, unit: "% YoY demand decline once past peak", direction: "down", delay_days: 0, duration_days: 3650, confidence: 0.68, source: "IEA World Energy Outlook 2024; BP Energy Outlook demand scenarios", children: ["brent_price_structural_slump", "capex_shift_to_electrons"] },
  { id: "capex_shift_to_electrons", event: "Upstream oil investment is diverted to grids, batteries, and renewables", detail: "IEA tracks clean energy investment exceeding fossil fuel investment; 2023 clean energy investment reached roughly $1.8 trillion per IEA.", sector: "energy", region: "global", magnitude: 1800, unit: "billion USD annual clean investment (2023 level, growing)", direction: "up", delay_days: 180, duration_days: 3650, confidence: 0.72, source: "IEA World Energy Investment 2024", children: ["renewables_manufacturing_boom"] },
  { id: "brent_price_structural_slump", event: "Spot oil prices trend lower as spare capacity meets flat demand", detail: "2014–2016 and 2020 episodes showed rapid oil price crashes when demand softens; long-run price needed to balance some petrostates has been estimated well above marginal cost for swing producers.", sector: "energy", region: "global", magnitude: 35, unit: "% price decline vs prior decade average (scenario)", direction: "down", delay_days: 90, duration_days: 1825, confidence: 0.6, source: "World Bank commodity markets outlook; OPEC Monthly Oil Market Report historical prices", children: ["petrostate_fiscal_stress", "personal_energy_bill_relief"] },
  { id: "petrostate_fiscal_stress", event: "Oil exporters cut budgets and subsidies as fiscal breakevens bite", detail: "IMF estimates fiscal breakeven oil prices often $60–$90+ for Gulf states; sustained lower prices force deficit spending or austerity.", sector: "energy", region: "middle-east", magnitude: 12, unit: "% of GDP fiscal gap (illustrative stress)", direction: "down", delay_days: 180, duration_days: 1825, confidence: 0.58, source: "IMF Regional Economic Outlook: Middle East and Central Asia", children: ["fx_and_debt_pressure"] },
  { id: "fx_and_debt_pressure", event: "Emerging oil currencies weaken and sovereign spreads widen", detail: "During 2014–2016 oil slump, RUB, NOK, CAD, and MXN moved sharply with crude; EM energy exporters saw CDS spreads rise.", sector: "currency", region: "emerging", magnitude: 25, unit: "% FX depreciation vs USD (episode analog)", direction: "down", delay_days: 120, duration_days: 1095, confidence: 0.57, source: "BIS effective exchange rate data; IMF external sector reports", children: ["imported_renewables_cost_advantage"] },
  { id: "imported_renewables_cost_advantage", event: "Cheaper imported solar/wind gear improves project IRR for developing grids", detail: "Lazard LCOE analyses show utility solar and wind at or below marginal fossil costs in many markets; currency moves can offset but equipment learning curves dominate.", sector: "energy", region: "emerging", magnitude: 40, unit: "% LCOE decline vs 2010 (historical)", direction: "down", delay_days: 365, duration_days: 3650, confidence: 0.7, source: "Lazard Levelized Cost of Energy Analysis; IRENA renewable cost database", children: ["renewables_manufacturing_boom"] },
  { id: "renewables_manufacturing_boom", event: "Battery, inverter, and turbine factories run at high utilization", detail: "U.S. IRA and EU Net-Zero Industry Act incentivize factory builds; IEA tracks strong jobs growth in clean energy employment—clean energy jobs reached roughly 30 million globally in IEA 2024 employment estimate.", sector: "employment", region: "global", magnitude: 30, unit: "million clean energy jobs (IEA order of magnitude)", direction: "up", delay_days: 365, duration_days: 3650, confidence: 0.67, source: "IEA World Energy Employment Report 2024", children: ["local_installer_and_grid_jobs"] },
  { id: "local_installer_and_grid_jobs", event: "Electrician, technician, and grid interconnection backlogs lift wages", detail: "U.S. BLS projects strong growth for solar installers; union and non-union training programs expanded under federal infrastructure laws.", sector: "employment", region: "us", magnitude: 22, unit: "% projected job growth 2022–2032 (solar installers BLS)", direction: "up", delay_days: 180, duration_days: 3650, confidence: 0.65, source: "U.S. Bureau of Labor Statistics Occupational Outlook (solar photovoltaic installers)", children: ["personal_green_career_uplift"] },
  { id: "personal_energy_bill_relief", event: "Your gasoline and heating oil spending falls with weaker crude", detail: "Retail gasoline correlates with Brent; households in car-dependent suburbs gain disposable income when oil prices structurally decline.", sector: "energy", region: "personal", magnitude: 18, unit: "% fuel expenditure reduction", direction: "down", delay_days: 60, duration_days: 1095, confidence: 0.62, source: "calculated from brent_price_structural_slump pass-through", children: [] },
  { id: "personal_green_career_uplift", event: "Your wages and hours rise in installation, maintenance, or factory roles", detail: "Entry-level solar installer and battery technician roles offer above-minimum compensation in many U.S. metros with overtime during buildouts.", sector: "employment", region: "personal", magnitude: 15, unit: "% wage premium vs retail/hospitality pivot", direction: "up", delay_days: 90, duration_days: 3650, confidence: 0.58, source: "calculated; BLS wage quartiles for installers", children: [] },
];

export const scenarios: Record<string, ScenarioData> = {
  hormuz_strait: {
    scenario: { name: "Hormuz Strait Blockade", description: "The Strait of Hormuz blocked due to Iran-Israel conflict. Largest oil disruption in history.", date: "2026-02-28", tags: ["war", "energy", "oil", "food"] },
    chain: { nodes: hormuzNodes, edges: buildEdges(hormuzNodes) },
  },
  dollar_crisis: {
    scenario: { name: "Dollar Reserve Collapse", description: "US dollar falls below 50% global reserves. De-dollarization accelerates. Gold breaches $6,000/oz.", date: "2026-06-01", tags: ["dollar", "currency", "gold", "brics"] },
    chain: { nodes: dollarNodes, edges: buildEdges(dollarNodes) },
  },
  ai_displacement: {
    scenario: { name: "AI Employment Displacement", description: "Agentic AI automates 40% of knowledge work. 92M jobs displaced, 170M new ones forming.", date: "2026-07-01", tags: ["ai", "employment", "automation", "skills"] },
    chain: { nodes: aiNodes, edges: buildEdges(aiNodes) },
  },
  pandemic_v2: {
    scenario: { name: "Next Pandemic (H5N1)", description: "Novel H5N1 variant achieves human transmission. Compound crisis atop war + AI disruption.", date: "2026-09-01", tags: ["pandemic", "health", "supply-chain"] },
    chain: { nodes: pandemicNodes, edges: buildEdges(pandemicNodes) },
  },
  taiwan_chips: {
    scenario: { name: "Taiwan Semiconductor Strait Crisis", description: "A military blockade of Taiwan disrupts wafer fabs and maritime lanes carrying advanced semiconductors. Taiwan produces the majority of the world’s contract foundry output; a sustained disruption propagates through electronics, autos, and labor markets.", date: "2026-06-15", tags: ["semiconductors", "taiwan", "trade", "technology", "autos", "geopolitics"] },
    chain: { nodes: taiwanNodes, edges: buildEdges(taiwanNodes) },
  },
  climate_food: {
    scenario: { name: "Synchronized Climate Crop Failure", description: "Concurrent record droughts and floods in major breadbaskets across South America, Europe, and Asia slash yields and trigger export restrictions. The shock propagates from grain markets to livestock, food inflation, and political stability.", date: "2026-08-01", tags: ["climate", "food", "agriculture", "inflation", "emerging-markets"] },
    chain: { nodes: climateNodes, edges: buildEdges(climateNodes) },
  },
  turkey_earthquake: {
    scenario: { name: "Marmara Megacity Earthquake", description: "A magnitude 7.5+ earthquake on the North Anatolian Fault under the Istanbul metropolitan area destroys critical infrastructure, displaces millions, and stresses Turkey’s economy, insurers, and housing markets.", date: "2026-04-12", tags: ["earthquake", "turkey", "istanbul", "housing", "insurance", "migration"] },
    chain: { nodes: earthquakeNodes, edges: buildEdges(earthquakeNodes) },
  },
  crypto_crash: {
    scenario: { name: "Stablecoin Contagion Crypto Crash", description: "A synchronized 80%+ drawdown in crypto assets together with major stablecoin depegs drains exchange and DeFi liquidity, hits funds and banks with crypto exposure, tightens credit, and freezes venture funding—culminating in tech labor cuts.", date: "2026-03-03", tags: ["crypto", "stablecoin", "finance", "vc", "layoffs", "credit"] },
    chain: { nodes: cryptoNodes, edges: buildEdges(cryptoNodes) },
  },
  energy_transition: {
    scenario: { name: "Accelerated Peak Oil Demand", description: "Electric vehicles, heat pumps, and efficiency gains push global oil demand past a structural peak. Prices for oil and related sovereigns fall sharply while renewables manufacturing and installation scale—creating localized booms and measurable personal upside for workers who transition.", date: "2026-01-20", tags: ["energy", "oil", "renewables", "employment", "climate", "transition"] },
    chain: { nodes: energyNodes, edges: buildEdges(energyNodes) },
  },
};

export default scenarios.hormuz_strait;
